routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('pages', App\Http\Controllers\PageController::class);

Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::resource('companies', App\Http\Controllers\CompanyController::class);

Route::group(['middleware' => 'auth'], function(){
    Route::get('jobs/{job}/approve', [App\Http\Controllers\JobController::class, 'approve'])->name('jobs.approve');
});

Route::resource('jobs', App\Http\Controllers\JobController::class);

Route::resource('tags', App\Http\Controllers\TagController::class);

Route::resource('users', App\Http\Controllers\UserController::class);

app/Models/Job.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Job
 * @package App\Models
 * @version June 15, 2022, 6:22 pm UTC
 *
 * @property \App\Models\Category $category
 * @property \App\Models\Company $company
 * @property \Illuminate\Database\Eloquent\Collection $tags
 * @property string $title
 * @property string $slug
 * @property integer $category_id
 * @property string $post_type
 * @property integer $salary_min
 * @property integer $salary_max
 * @property string $salary_type
 * @property boolean $negotiable
 * @property string $start_date
 * @property string $country
 * @property string $contact_name
 * @property string $city
 * @property boolean $accept_terms
 * @property integer $company_id
 */
class Job extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'jobs';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'slug',
        'category_id',
        'post_type',
        'salary_min',
        'salary_max',
        'salary_type',
        'negotiable',
        'start_date',
        'status',
        'excerpt',
        'description',
        'country',
        'contact_name',
        'city',
        'accept_terms',
        'company_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'slug' => 'string',
        'category_id' => 'integer',
        'post_type' => 'string',
        'salary_min' => 'integer',
        'salary_max' => 'integer',
        'salary_type' => 'string',
        'negotiable' => 'boolean',
        'country' => 'string',
        'contact_name' => 'string',
        'city' => 'string',
        'captcha' => 'string',
        'accept_terms' => 'boolean',
        'company_id' => 'integer'
    ];

    public static $types = [
        'full-time' => 'Full time',
        'part-time' => 'Part time',
        'temporary' => 'Temporary',
        'contract' => 'Contract',
        'internship' => 'Internship',
        'permanent' => 'Permanent',
        'optional' => 'Optional'
    ];

    public static $commute = [
        'remote' => 'Remote',
        'on-site' => 'On site',
        'optional' => 'Optional'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'required|max:128',
        'slug' => 'max:128',
        'category_id' => 'required',
        'start_date' => 'required|date',
        'description' => 'string|required',
        'excerpt' => 'string|required|max:256',
        'country' => 'required|max:2|min:2',
        'city' => 'required',
        'captcha' => 'required',
        'accept_terms' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function category()
    {
        return $this->belongsTo(\App\Models\Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function company()
    {
        return $this->belongsTo(\App\Models\Company::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function tags()
    {
        return $this->belongsToMany(\App\Models\Tag::class);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJobRequest;
use App\Http\Requests\UpdateJobRequest;
use App\Models\Company;
use App\Models\Job;
use App\Models\Tag;
use App\Notifications\JobPublished;
use App\Notifications\NewJob;
use App\Repositories\JobRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;
use Laracasts\Flash\Flash;
use Response;

class JobController extends AppBaseController
{
    /** @var JobRepository $jobRepository*/
    private $jobRepository;

    public function __construct(JobRepository $jobRepo)
    {
        $this->jobRepository = $jobRepo;
    }

    /**
     * Display a listing of the Job.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $jobs = auth_admin() ? $this->jobRepository->all() : Job::where('status', 'published')->get();

        return view('jobs.index')
            ->with('jobs', $jobs);
    }

    /**
     * Show the form for creating a new Job.
     *
     * @return Response
     */
    public function create()
    {
        return view('jobs.create');
    }

    /**
     * Store a newly created Job in storage.
     *
     * @param CreateJobRequest $request
     *
     * @return Response
     */
    public function store(CreateJobRequest $request)
    {
        $company = Company::firstOrCreate(
            [ 'email' => $request->email ],
            $request->only(['name', 'email', 'logo', 'banner', 'description', 'phone'])
        );
        $computed = [
            'slug' => slug($request->title) . '_' . strtolower(\Str::random(3)),
            'company_id' => $company->id,
            'excerpt' => nl2br($request->excerpt)
        ];
        $input = array_merge($request->all(), $computed);

        $job = $this->jobRepository->create($input);

        $tags = explode(',', $request->tags);
        foreach ($tags as $tag) {
            $new_tag = Tag::firstOrCreate(['name' => $tag]);
            $job->tags()->attach($new_tag->id);
        }

        if($request->logo) {
            $logo = $request->file('logo');
            $filename = $company->id . '_' . slug($company->name) . '.' . $logo->extension();
            $logo->move('storage/logos/', $filename);
            $company->logo = "storage/logos/$filename";
            $company->save();
        }

        foreach (User::where('role', 'admin')->get() as $admin) {
            Notification::send($admin, new NewJob($job));
        }

        Flash::success('Job saved successfully.');

        return redirect(route('jobs.index'));
    }

    /**
     * Display the specified Job.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $job = $this->jobRepository->find($id);

        if (empty($job)) {
            Flash::error('Job not found');

            return redirect(route('jobs.index'));
        }

        return view('jobs.show')->with('job', $job);
    }

    /**
     * Show the form for editing the specified Job.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $job = $this->jobRepository->find($id);

        if (empty($job)) {
            Flash::error('Job not found');

            return redirect(route('jobs.index'));
        }

        return view('jobs.edit')->with('job', $job);
    }

    /**
     * Update the specified Job in storage.
     *
     * @param int $id
     * @param UpdateJobRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJobRequest $request)
    {
        $job = $this->jobRepository->find($id);

        if (empty($job)) {
            Flash::error('Job not found');

            return redirect(route('jobs.index'));
        }

        $job = $this->jobRepository->update($request->all(), $id);

        Flash::success('Job updated successfully.');

        return redirect(route('jobs.index'));
    }

    /**
     * Remove the specified Job from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $job = $this->jobRepository->find($id);

        if (empty($job)) {
            Flash::error('Job not found');

            return redirect(route('jobs.index'));
        }

        $this->jobRepository->delete($id);

        Flash::success('Job deleted successfully.');

        return redirect(route('jobs.index'));
    }

    public function approve($id)
    {
        if (!auth_admin())
            abort(403, 'You\'re not allowed to do that!');

        $job = $this->jobRepository->find($id);

        $job->status = 'published';
        $job->save();

        Notification::send($job->company, new \App\Notifications\JobPublished($job));

        Flash::success('Job approved successfully.');

        return redirect()->back();
    }
}

resources/views/jobs/apply_form.blade.php
    <div class="card profile-widget">
        <form method="post" class="needs-validation" novalidate="">
            <div class="card-header">
                <h4>Apply</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-12">
                        <label>First Name</label>
                        <input type="text" class="form-control" value="" required="">
                        <div class="invalid-feedback">
                            Please fill in the first name
                        </div>
                    </div>
                    <div class="form-group col-12">
                        <label>Last Name</label>
                        <input type="text" class="form-control" value="" required="">
                        <div class="invalid-feedback">
                            Please fill in the last name
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-12">
                        <label>Email</label>
                        <input type="email" class="form-control" value="" required="">
                        <div class="invalid-feedback">
                            Please fill in the email
                        </div>
                    </div>
                    <div class="form-group col-12">
                        <label>Phone</label>
                        <input type="tel" class="form-control" value="">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-12">
                        <label>Message</label>
                        <textarea class="form-control summernote-simple"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-12">
                        <label>Upload CV</label>
                        <input type="file" class="form-control" accept="application/pdf" required="">
                        <div class="invalid-feedback">
                            Please fill in the email
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                <button class="btn btn-primary">Send application</button>
            </div>
        </form>
    </div>

resources/views/jobs/create.blade.php
@extends('layouts.app')
@section('title')
    Create Job 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Job</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('jobs.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'jobs.store', 'enctype' => 'multipart/form-data']) !!}
                                    @include('jobs.fields')
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/jobs/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Job 
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit Job</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('jobs.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($job, ['route' => ['jobs.update', $job->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('jobs.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/jobs/index.blade.php
@extends('layouts.app')
@section('title')
    Jobs
@endsection
@section('results-title')
    {{ __ucf('all jobs') }}
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Jobs</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('jobs.create')}}" class="btn btn-primary form-btn">Job <i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('jobs.table')
            </div>
       </div>
   </div>

    </section>
@endsection

resources/views/jobs/show.blade.php
@extends('layouts.app')
@section('title')
    {{ $job->title }}
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>{{ $job->title }}</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('jobs.index') }}"
                   class="btn btn-primary form-btn float-right">Back</a>
            </div>
        </div>
        @include('stisla-templates::common.errors')
        <div class="section-body">
            <div class="row mt-sm-4">
                <div class="col-12 col-md-12 col-lg-7">
                    @include('jobs.show_fields')
                </div>
                <div class="col-12 col-md-12 col-lg-5">
                    @include('jobs.apply_form')
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/jobs/show_fields.blade.php
<div class="card profile-widget">
    <div class="profile-widget-header">
        <img alt="{{ $job->company->name }}"
             src="{{ asset($job->company->logo ?? 'assets/images/missing-logo.svg') }}" class="job-details-logo">
        <div class="profile-widget-items">
            <div class="profile-widget-item">
                <div class="profile-widget-item-label">Min salary</div>
                <div class="profile-widget-item-value">{{ money($job->salary_min) }}</div>
            </div>
            <div class="profile-widget-item">
                <div class="profile-widget-item-label">Max salary</div>
                <div class="profile-widget-item-value">{{ money($job->salary_min) }}</div>
            </div>
            <div class="profile-widget-item">
                <div class="profile-widget-item-label">Start date</div>
                <div class="profile-widget-item-value">{{ human_date($job->start_date) }}</div>
            </div>
        </div>
    </div>
    <div class="profile-widget-description">
        <div class="profile-widget-name">{{ $job->title }}
            <div class="text-muted d-inline font-weight-normal">
                <div class="slash"></div> {{ $job->company->name }}</div>
        </div>
        {!! $job->description !!}
    </div>
    <div class="card-footer">
        <div class="mb-2">
            <span class="font-weight-bold">Category: </span><a href="{{ route('categories.show', $job->category) }}"
                                                               class="text-info">{{ $job->category->name }}</a>
        </div>
        @if ($job->tags->count())
            <div class="mb-2">
                <span class="font-weight-bold">Tags: </span>
                @foreach ($job->tags as $tag)
                    <a href="{{ route('tags.show', $tag) }}" class="btn-sm btn-info"><i
                            class="fa fa-tag mr-1"></i>{{ $tag->name }}</a>
                @endforeach
            </div>
        @endif
        @if(auth_admin() && $job->status == 'pending')
            <a href="{{ route('jobs.approve', $job) }}" class="btn btn-warning">Approve</a>
        @endif
    </div>
</div>
<div class="card">
    <div class="card-header">
        <h4>About the company</h4>
    </div>
    <div class="card-body">
        <h6 class="font-weight-bold">
            <a href="{{ route('companies.show', $job->company) }}">{{ $job->company->name }}</a>
        </h6>
        {!! $job->company->description !!}
    </div>
</div>

resources/views/jobs/table.blade.php
<div class="search-results-container">
    <div class="card">
        <div class="card-header">
            <h4>@yield('results-title')</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled list-unstyled-border">
            @foreach($jobs as $job)
                <li class="media results-item">
                    <div class="result-item-logo mr-3 mb-2">
                        <a href="{{ route('companies.show', $job->company) }}">
                            <img class="w-100" src="{{ asset($job->company->logo ?? 'assets/images/missing-logo.svg') }}" alt="logo" width="50">
                        </a>
                    </div>
                    <div class="media-body">
                        <div class="float-right text-primary">
                            <ul class="results-item-details">
                                <li>
                                    <i class="fa fa-disk"></i><span>{{ __ucf('salary') }}</span>{{ money($job->salary_min) }} to {{ money($job->salary_max) }} per {{ $job->salary_type }}
                                    @if ($job->negotiable)
                                        <br><span class="text-small text-info">{{ __ucf('Negotiable') }}</span>
                                    @endif
                                </li>
                                <li>
                                    @if(auth_admin() && $job->status !== 'published')
                                        <a href="{{ route('jobs.approve', $job) }}" class="btn btn-warning">Approve</a>
                                    @endif
                                </li>
                            </ul>
                        </div>
                        <div class="media-title">
                            <a href="{{ route('jobs.show', $job) }}">{{ $job->title }}</a>
                        </div>
                        <ul class="text-small text-muted ul-inline">
                            <li><i class="fa fa-disk"></i><span>{{ __ucf('post type') }}: </span>{{ $job->post_type }}</li>
                            <li><i class="fa fa-disk"></i><span>{{ __ucf('start date') }}: </span>{{ human_date($job->start_date) }}</li>
                        </ul>
                        <div class="results-item-description">
                            <p>{!! $job->excerpt !!}</p>
                        </div>
                        <div class="results-item-footer">
                            <ul class="results-item-meta text-small text-muted ul-inline">
                                <li><i class="fa fa-briefcase"></i><span>{{ __ucf('category') }}: </span>{{ $job->category->name }}</li>
                                <li><i class="fa fa-map-pin"></i><span>{{ __ucf('location') }}: </span>{{ $job->city }}, {{ \App\Models\Country::$list[$job->country] }}</li>
                                <li><i class="fa fa-user"></i><span>{{ __ucf('contact') }} </span>{{ $job->contact_name }}</li>
                            </ul>
                            <ul class="results-item-tags ul-inline">
                                @foreach($job->tags as $tag)
                                    <li><i class="fa fa-tag"></i><span>{{ __ucf($tag->name) }}</span></li>
                                @endforeach
                            </ul>
                            @if(auth()->user()?->is_admin())
                                <div class="results-item-actions text-center">
                                    {!! Form::open(['route' => ['jobs.destroy', $job->id], 'method' => 'delete']) !!}
                                    <div class='btn-group'>
                                        <a href="{!! route('jobs.show', [$job->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                                        <a href="{!! route('jobs.edit', [$job->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                                    </div>
                                    {!! Form::close() !!}
                                </div>
                            @endif
                        </div>
                    </div>
                </li>
            @endforeach
            </ul>
            <div class="text-center pt-1 pb-1">
                <a href="{{ route('jobs.index') }}" class="btn btn-primary btn-lg btn-round">
                    View All
                </a>
            </div>
        </div>
    </div>
</div>